[2024-10-04T12:02:37.822+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T12:02:37.837+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: decision_tree_classifier_dag.dtc_get_data manual__2024-10-04T12:02:34.084710+00:00 [queued]>
[2024-10-04T12:02:37.845+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: decision_tree_classifier_dag.dtc_get_data manual__2024-10-04T12:02:34.084710+00:00 [queued]>
[2024-10-04T12:02:37.846+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-04T12:02:37.861+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dtc_get_data> on 2024-10-04 12:02:34.084710+00:00
[2024-10-04T12:02:37.869+0000] {standard_task_runner.py:64} INFO - Started process 56720 to run task
[2024-10-04T12:02:37.872+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'decision_tree_classifier_dag', 'dtc_get_data', 'manual__2024-10-04T12:02:34.084710+00:00', '--job-id', '805', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/hw1.py', '--cfg-path', '/tmp/tmpf4l3k711']
[2024-10-04T12:02:37.874+0000] {standard_task_runner.py:91} INFO - Job 805: Subtask dtc_get_data
[2024-10-04T12:02:37.915+0000] {task_command.py:426} INFO - Running <TaskInstance: decision_tree_classifier_dag.dtc_get_data manual__2024-10-04T12:02:34.084710+00:00 [running]> on host 4b5f1410d111
[2024-10-04T12:02:37.997+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='decision_tree_classifier_dag' AIRFLOW_CTX_TASK_ID='dtc_get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T12:02:34.084710+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T12:02:34.084710+00:00'
[2024-10-04T12:02:37.998+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T12:02:38.008+0000] {hw1.py:91} INFO - Get data...
[2024-10-04T12:02:38.419+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T12:02:38.420+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T12:02:38.999+0000] {hw1.py:103} INFO - Finish get data.
[2024-10-04T12:02:39.000+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T12:02:39.001+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T12:02:39.019+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=decision_tree_classifier_dag, task_id=dtc_get_data, run_id=manual__2024-10-04T12:02:34.084710+00:00, execution_date=20241004T120234, start_date=20241004T120237, end_date=20241004T120239
[2024-10-04T12:02:39.050+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T12:02:39.072+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T12:02:39.074+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
