[2024-09-24T15:42:54.623+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-24T15:42:54.641+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train.data_preparation scheduled__2024-09-23T01:00:00+00:00 [queued]>
[2024-09-24T15:42:54.650+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train.data_preparation scheduled__2024-09-23T01:00:00+00:00 [queued]>
[2024-09-24T15:42:54.651+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-24T15:42:54.665+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_preparation> on 2024-09-23 01:00:00+00:00
[2024-09-24T15:42:54.676+0000] {standard_task_runner.py:64} INFO - Started process 534 to run task
[2024-09-24T15:42:54.684+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train', 'data_preparation', 'scheduled__2024-09-23T01:00:00+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/1_train_dag-checkpoint.py', '--cfg-path', '/tmp/tmpg03hf3cb']
[2024-09-24T15:42:54.686+0000] {standard_task_runner.py:91} INFO - Job 318: Subtask data_preparation
[2024-09-24T15:42:54.735+0000] {task_command.py:426} INFO - Running <TaskInstance: train.data_preparation scheduled__2024-09-23T01:00:00+00:00 [running]> on host 82997fc6deb7
[2024-09-24T15:42:54.824+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='train' AIRFLOW_CTX_TASK_ID='data_preparation' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T01:00:00+00:00'
[2024-09-24T15:42:54.825+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-24T15:42:54.838+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path 2024/datasets/california_housing.pkl
[2024-09-24T15:42:54.847+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T15:42:54.848+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T15:42:56.242+0000] {1_train_dag-checkpoint.py:127} INFO - Data prepared.
[2024-09-24T15:42:56.247+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-24T15:42:56.248+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-24T15:42:56.260+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=train, task_id=data_preparation, run_id=scheduled__2024-09-23T01:00:00+00:00, execution_date=20240923T010000, start_date=20240924T154254, end_date=20240924T154256
[2024-09-24T15:42:56.307+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-24T15:42:56.338+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-24T15:42:56.342+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
