[2024-10-04T14:13:12.549+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T14:13:12.564+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Alex_Trigolos.training_gbc_model_tasks manual__2024-10-04T14:12:59.018529+00:00 [queued]>
[2024-10-04T14:13:12.573+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Alex_Trigolos.training_gbc_model_tasks manual__2024-10-04T14:12:59.018529+00:00 [queued]>
[2024-10-04T14:13:12.574+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-04T14:13:12.588+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): training_gbc_model_tasks> on 2024-10-04 14:12:59.018529+00:00
[2024-10-04T14:13:12.597+0000] {standard_task_runner.py:64} INFO - Started process 9762 to run task
[2024-10-04T14:13:12.601+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Alex_Trigolos', 'training_gbc_model_tasks', 'manual__2024-10-04T14:12:59.018529+00:00', '--job-id', '909', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/project-checkpoint.py', '--cfg-path', '/tmp/tmphbch5vta']
[2024-10-04T14:13:12.604+0000] {standard_task_runner.py:91} INFO - Job 909: Subtask training_gbc_model_tasks
[2024-10-04T14:13:12.651+0000] {task_command.py:426} INFO - Running <TaskInstance: Alex_Trigolos.training_gbc_model_tasks manual__2024-10-04T14:12:59.018529+00:00 [running]> on host 4b5f1410d111
[2024-10-04T14:13:12.760+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='Alex_Trigolos' AIRFLOW_CTX_TASK_ID='training_gbc_model_tasks' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T14:12:59.018529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T14:12:59.018529+00:00'
[2024-10-04T14:13:12.761+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T14:13:12.775+0000] {project-checkpoint.py:162} INFO - Train model...
[2024-10-04T14:13:12.794+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/project/datasets/X_train.pkl
[2024-10-04T14:13:12.802+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T14:13:12.803+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T14:13:13.040+0000] {project-checkpoint.py:92} INFO - /tmp/***_tmp_zeizq6vz
[2024-10-04T14:13:13.046+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/project/datasets/X_val.pkl
[2024-10-04T14:13:13.053+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T14:13:13.054+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T14:13:13.255+0000] {project-checkpoint.py:92} INFO - /tmp/***_tmp_6gg5fyxh
[2024-10-04T14:13:13.258+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/project/datasets/X_test.pkl
[2024-10-04T14:13:13.266+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T14:13:13.267+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T14:13:13.721+0000] {project-checkpoint.py:92} INFO - /tmp/***_tmp_u6050fwk
[2024-10-04T14:13:13.723+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/project/datasets/y_train.pkl
[2024-10-04T14:13:13.731+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T14:13:13.732+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T14:13:13.916+0000] {project-checkpoint.py:92} INFO - /tmp/***_tmp_ph40ei5k
[2024-10-04T14:13:13.919+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/project/datasets/y_val.pkl
[2024-10-04T14:13:13.926+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T14:13:13.927+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T14:13:14.113+0000] {project-checkpoint.py:92} INFO - /tmp/***_tmp_k9wqg36y
[2024-10-04T14:13:14.116+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/project/datasets/y_test.pkl
[2024-10-04T14:13:14.123+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T14:13:14.124+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T14:13:14.291+0000] {project-checkpoint.py:92} INFO - /tmp/***_tmp_vo8gpnea
[2024-10-04T14:13:14.383+0000] {logging_mixin.py:188} WARNING - 2024/10/04 14:13:14 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-10-04T14:13:14.417+0000] {logging_mixin.py:188} INFO - Fitting 5 folds for each of 1080 candidates, totalling 5400 fits
[2024-10-04T15:43:44.792+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/mlflow/types/utils.py:406 UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2024-10-04T15:43:50.731+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-10-04T15:43:51.141+0000] {configprovider.py:957} INFO - Found endpoint for s3 via: environment_global.
[2024-10-04T15:43:51.618+0000] {logging_mixin.py:188} WARNING - Registered model 'sk-learn-GradientBoostingClassifier-model' already exists. Creating a new version of this model...
[2024-10-04T15:43:51.676+0000] {logging_mixin.py:188} WARNING - 2024/10/04 15:43:51 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: sk-learn-GradientBoostingClassifier-model, version 5
[2024-10-04T15:43:51.676+0000] {logging_mixin.py:188} WARNING - Created version '5' of model 'sk-learn-GradientBoostingClassifier-model'.
[2024-10-04T15:43:53.016+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/mlflow/types/utils.py:406 UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2024-10-04T15:43:53.096+0000] {logging_mixin.py:188} WARNING - 2024/10/04 15:43:53 INFO mlflow.models.evaluation.default_evaluator: Computing model predictions.
[2024-10-04T15:43:53.102+0000] {logging_mixin.py:188} WARNING - 2024/10/04 15:43:53 INFO mlflow.models.evaluation.default_evaluator: The evaluation dataset is inferred as binary dataset, positive label is 1, negative label is 0.
[2024-10-04T15:43:53.129+0000] {logging_mixin.py:188} WARNING - 2024/10/04 15:43:53 INFO mlflow.models.evaluation.default_evaluator: Testing metrics on first row...
[2024-10-04T15:43:55.227+0000] {logging_mixin.py:188} WARNING - 2024/10/04 15:43:55 WARNING mlflow.models.evaluation.default_evaluator: Skip logging model explainability insights because the shap explainer None requires all feature values to be numeric, and each feature column must only contain scalar values.
[2024-10-04T15:43:55.326+0000] {logging_mixin.py:188} WARNING - 2024/10/04 15:43:55 INFO mlflow.tracking._tracking_service.client: üèÉ View run GradientBoostingClassifier at: http://mlflow-service:5000/#/experiments/128330878462801848/runs/b9380731d1134489a41be36e9c3ecee3.
[2024-10-04T15:43:55.328+0000] {logging_mixin.py:188} WARNING - 2024/10/04 15:43:55 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow-service:5000/#/experiments/128330878462801848.
[2024-10-04T15:43:55.353+0000] {project-checkpoint.py:206} INFO - Finish model train.
[2024-10-04T15:43:55.357+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T15:43:55.359+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T15:43:55.373+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Alex_Trigolos, task_id=training_gbc_model_tasks, run_id=manual__2024-10-04T14:12:59.018529+00:00, execution_date=20241004T141259, start_date=20241004T141312, end_date=20241004T154355
[2024-10-04T15:43:55.468+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T15:43:55.524+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T15:43:55.533+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
