[2024-09-24T18:56:24.801+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-24T18:56:24.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: decision_tree_classifier_dag.dtc_train_model manual__2024-09-24T18:56:16.066939+00:00 [queued]>
[2024-09-24T18:56:24.820+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: decision_tree_classifier_dag.dtc_train_model manual__2024-09-24T18:56:16.066939+00:00 [queued]>
[2024-09-24T18:56:24.822+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-24T18:56:24.831+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dtc_train_model> on 2024-09-24 18:56:16.066939+00:00
[2024-09-24T18:56:24.839+0000] {standard_task_runner.py:64} INFO - Started process 49699 to run task
[2024-09-24T18:56:24.842+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'decision_tree_classifier_dag', 'dtc_train_model', 'manual__2024-09-24T18:56:16.066939+00:00', '--job-id', '488', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/hw1-checkpoint.py', '--cfg-path', '/tmp/tmpsy4ldphx']
[2024-09-24T18:56:24.844+0000] {standard_task_runner.py:91} INFO - Job 488: Subtask dtc_train_model
[2024-09-24T18:56:24.888+0000] {task_command.py:426} INFO - Running <TaskInstance: decision_tree_classifier_dag.dtc_train_model manual__2024-09-24T18:56:16.066939+00:00 [running]> on host 82997fc6deb7
[2024-09-24T18:56:24.968+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='decision_tree_classifier_dag' AIRFLOW_CTX_TASK_ID='dtc_train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T18:56:16.066939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-24T18:56:16.066939+00:00'
[2024-09-24T18:56:24.969+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-24T18:56:24.979+0000] {hw1-checkpoint.py:145} INFO - Train model...
[2024-09-24T18:56:24.980+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/DecisionTreeClassifier/datasets/X_train.pkl
[2024-09-24T18:56:24.987+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T18:56:24.988+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T18:56:25.339+0000] {hw1-checkpoint.py:86} INFO - /tmp/***_tmp_3aguumfg
[2024-09-24T18:56:25.342+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/DecisionTreeClassifier/datasets/X_test.pkl
[2024-09-24T18:56:25.348+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T18:56:25.349+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T18:56:25.521+0000] {hw1-checkpoint.py:86} INFO - /tmp/***_tmp_i_dmzpkg
[2024-09-24T18:56:25.524+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/DecisionTreeClassifier/datasets/y_train.pkl
[2024-09-24T18:56:25.530+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T18:56:25.531+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T18:56:25.681+0000] {hw1-checkpoint.py:86} INFO - /tmp/***_tmp_rw5ppn00
[2024-09-24T18:56:25.684+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/DecisionTreeClassifier/datasets/y_test.pkl
[2024-09-24T18:56:25.690+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T18:56:25.690+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T18:56:26.033+0000] {hw1-checkpoint.py:86} INFO - /tmp/***_tmp_on4vp3uo
[2024-09-24T18:56:26.039+0000] {logging_mixin.py:188} INFO - Fitting 5 folds for each of 4 candidates, totalling 20 fits
[2024-09-24T18:56:26.043+0000] {logging_mixin.py:188} INFO - [CV] END ................max_depth=None, min_samples_split=1; total time=   0.0s
[2024-09-24T18:56:26.045+0000] {logging_mixin.py:188} INFO - [CV] END ................max_depth=None, min_samples_split=1; total time=   0.0s
[2024-09-24T18:56:26.048+0000] {logging_mixin.py:188} INFO - [CV] END ................max_depth=None, min_samples_split=1; total time=   0.0s
[2024-09-24T18:56:26.049+0000] {logging_mixin.py:188} INFO - [CV] END ................max_depth=None, min_samples_split=1; total time=   0.0s
[2024-09-24T18:56:26.051+0000] {logging_mixin.py:188} INFO - [CV] END ................max_depth=None, min_samples_split=1; total time=   0.0s
[2024-09-24T18:56:26.057+0000] {logging_mixin.py:188} INFO - [CV] END ...............max_depth=None, min_samples_split=10; total time=   0.0s
[2024-09-24T18:56:26.062+0000] {logging_mixin.py:188} INFO - [CV] END ...............max_depth=None, min_samples_split=10; total time=   0.0s
[2024-09-24T18:56:26.066+0000] {logging_mixin.py:188} INFO - [CV] END ...............max_depth=None, min_samples_split=10; total time=   0.0s
[2024-09-24T18:56:26.071+0000] {logging_mixin.py:188} INFO - [CV] END ...............max_depth=None, min_samples_split=10; total time=   0.0s
[2024-09-24T18:56:26.076+0000] {logging_mixin.py:188} INFO - [CV] END ...............max_depth=None, min_samples_split=10; total time=   0.0s
[2024-09-24T18:56:26.078+0000] {logging_mixin.py:188} INFO - [CV] END ...................max_depth=1, min_samples_split=1; total time=   0.0s
[2024-09-24T18:56:26.079+0000] {logging_mixin.py:188} INFO - [CV] END ...................max_depth=1, min_samples_split=1; total time=   0.0s
[2024-09-24T18:56:26.081+0000] {logging_mixin.py:188} INFO - [CV] END ...................max_depth=1, min_samples_split=1; total time=   0.0s
[2024-09-24T18:56:26.082+0000] {logging_mixin.py:188} INFO - [CV] END ...................max_depth=1, min_samples_split=1; total time=   0.0s
[2024-09-24T18:56:26.084+0000] {logging_mixin.py:188} INFO - [CV] END ...................max_depth=1, min_samples_split=1; total time=   0.0s
[2024-09-24T18:56:26.091+0000] {logging_mixin.py:188} INFO - [CV] END ..................max_depth=1, min_samples_split=10; total time=   0.0s
[2024-09-24T18:56:26.096+0000] {logging_mixin.py:188} INFO - [CV] END ..................max_depth=1, min_samples_split=10; total time=   0.0s
[2024-09-24T18:56:26.101+0000] {logging_mixin.py:188} INFO - [CV] END ..................max_depth=1, min_samples_split=10; total time=   0.0s
[2024-09-24T18:56:26.107+0000] {logging_mixin.py:188} INFO - [CV] END ..................max_depth=1, min_samples_split=10; total time=   0.0s
[2024-09-24T18:56:26.114+0000] {logging_mixin.py:188} INFO - [CV] END ..................max_depth=1, min_samples_split=10; total time=   0.0s
[2024-09-24T18:56:26.119+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:540 FitFailedWarning:
10 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/home/***/.local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/***/.local/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/home/***/.local/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/***/.local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.
[2024-09-24T18:56:26.122+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/model_selection/_search.py:1102 UserWarning: One or more of the test scores are non-finite: [      nan 0.786536        nan 0.7878755]
[2024-09-24T18:56:26.183+0000] {hw1-checkpoint.py:171} INFO - Finish model train.
[2024-09-24T18:56:26.184+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-24T18:56:26.185+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-24T18:56:26.192+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=decision_tree_classifier_dag, task_id=dtc_train_model, run_id=manual__2024-09-24T18:56:16.066939+00:00, execution_date=20240924T185616, start_date=20240924T185624, end_date=20240924T185626
[2024-09-24T18:56:26.220+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-24T18:56:26.236+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-24T18:56:26.238+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
