[2024-10-04T06:38:46.709+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T06:38:46.723+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_forest_classifier_dag.rfc_prepare_data scheduled__2024-10-03T01:00:00+00:00 [queued]>
[2024-10-04T06:38:46.730+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_forest_classifier_dag.rfc_prepare_data scheduled__2024-10-03T01:00:00+00:00 [queued]>
[2024-10-04T06:38:46.731+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-04T06:38:46.741+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): rfc_prepare_data> on 2024-10-03 01:00:00+00:00
[2024-10-04T06:38:46.749+0000] {standard_task_runner.py:64} INFO - Started process 49223 to run task
[2024-10-04T06:38:46.752+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_forest_classifier_dag', 'rfc_prepare_data', 'scheduled__2024-10-03T01:00:00+00:00', '--job-id', '776', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/hw1-checkpoint.py', '--cfg-path', '/tmp/tmpgnzw2nfx']
[2024-10-04T06:38:46.754+0000] {standard_task_runner.py:91} INFO - Job 776: Subtask rfc_prepare_data
[2024-10-04T06:38:46.797+0000] {task_command.py:426} INFO - Running <TaskInstance: random_forest_classifier_dag.rfc_prepare_data scheduled__2024-10-03T01:00:00+00:00 [running]> on host 4b5f1410d111
[2024-10-04T06:38:46.876+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='random_forest_classifier_dag' AIRFLOW_CTX_TASK_ID='rfc_prepare_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T01:00:00+00:00'
[2024-10-04T06:38:46.878+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T06:38:46.887+0000] {hw1-checkpoint.py:107} INFO - Prepare data...
[2024-10-04T06:38:46.888+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/RandomForestClassifier/datasets/dataset.pkl
[2024-10-04T06:38:46.897+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T06:38:46.898+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T06:38:47.310+0000] {hw1-checkpoint.py:78} INFO - /tmp/***_tmp_kobt0p3q
[2024-10-04T06:38:47.388+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T06:38:47.388+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T06:38:47.716+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T06:38:47.717+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T06:38:47.857+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T06:38:47.858+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T06:38:47.997+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-04T06:38:47.998+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-04T06:38:48.482+0000] {hw1-checkpoint.py:133} INFO - Prepared data.
[2024-10-04T06:38:48.483+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T06:38:48.484+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T06:38:48.496+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=random_forest_classifier_dag, task_id=rfc_prepare_data, run_id=scheduled__2024-10-03T01:00:00+00:00, execution_date=20241003T010000, start_date=20241004T063846, end_date=20241004T063848
[2024-10-04T06:38:48.532+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T06:38:48.564+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T06:38:48.566+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
