[2024-09-24T18:54:14.730+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-24T18:54:14.743+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_forest_classifier_dag.rfc_train_model manual__2024-09-24T18:54:05.214006+00:00 [queued]>
[2024-09-24T18:54:14.749+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_forest_classifier_dag.rfc_train_model manual__2024-09-24T18:54:05.214006+00:00 [queued]>
[2024-09-24T18:54:14.750+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-24T18:54:14.760+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): rfc_train_model> on 2024-09-24 18:54:05.214006+00:00
[2024-09-24T18:54:14.768+0000] {standard_task_runner.py:64} INFO - Started process 48779 to run task
[2024-09-24T18:54:14.770+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_forest_classifier_dag', 'rfc_train_model', 'manual__2024-09-24T18:54:05.214006+00:00', '--job-id', '473', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/hw1-checkpoint.py', '--cfg-path', '/tmp/tmpnox1xfs5']
[2024-09-24T18:54:14.773+0000] {standard_task_runner.py:91} INFO - Job 473: Subtask rfc_train_model
[2024-09-24T18:54:14.809+0000] {task_command.py:426} INFO - Running <TaskInstance: random_forest_classifier_dag.rfc_train_model manual__2024-09-24T18:54:05.214006+00:00 [running]> on host 82997fc6deb7
[2024-09-24T18:54:14.872+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='random_forest_classifier_dag' AIRFLOW_CTX_TASK_ID='rfc_train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T18:54:05.214006+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-24T18:54:05.214006+00:00'
[2024-09-24T18:54:14.874+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-24T18:54:14.883+0000] {hw1-checkpoint.py:145} INFO - Train model...
[2024-09-24T18:54:14.884+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/RandomForestClassifier/datasets/X_train.pkl
[2024-09-24T18:54:14.891+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T18:54:14.892+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T18:54:15.244+0000] {hw1-checkpoint.py:86} INFO - /tmp/***_tmp_qehct2gg
[2024-09-24T18:54:15.246+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/RandomForestClassifier/datasets/X_test.pkl
[2024-09-24T18:54:15.253+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T18:54:15.254+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T18:54:15.406+0000] {hw1-checkpoint.py:86} INFO - /tmp/***_tmp_k49cr47x
[2024-09-24T18:54:15.408+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/RandomForestClassifier/datasets/y_train.pkl
[2024-09-24T18:54:15.414+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T18:54:15.415+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T18:54:15.628+0000] {hw1-checkpoint.py:86} INFO - /tmp/***_tmp_1xqw_108
[2024-09-24T18:54:15.630+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/RandomForestClassifier/datasets/y_test.pkl
[2024-09-24T18:54:15.636+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T18:54:15.637+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T18:54:16.009+0000] {hw1-checkpoint.py:86} INFO - /tmp/***_tmp_8lkp3bxx
[2024-09-24T18:54:16.015+0000] {logging_mixin.py:188} INFO - Fitting 5 folds for each of 4 candidates, totalling 20 fits
[2024-09-24T18:54:16.019+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=None, min_samples_split=1, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.021+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=None, min_samples_split=1, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.022+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=None, min_samples_split=1, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.024+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=None, min_samples_split=1, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.025+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=None, min_samples_split=1, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.073+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=None, min_samples_split=10, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.123+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=None, min_samples_split=10, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.172+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=None, min_samples_split=10, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.220+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=None, min_samples_split=10, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.270+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=None, min_samples_split=10, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.272+0000] {logging_mixin.py:188} INFO - [CV] END .max_depth=30, min_samples_split=1, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.274+0000] {logging_mixin.py:188} INFO - [CV] END .max_depth=30, min_samples_split=1, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.275+0000] {logging_mixin.py:188} INFO - [CV] END .max_depth=30, min_samples_split=1, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.276+0000] {logging_mixin.py:188} INFO - [CV] END .max_depth=30, min_samples_split=1, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.278+0000] {logging_mixin.py:188} INFO - [CV] END .max_depth=30, min_samples_split=1, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.326+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=30, min_samples_split=10, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.373+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=30, min_samples_split=10, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.421+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=30, min_samples_split=10, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.468+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=30, min_samples_split=10, n_estimators=50; total time=   0.0s
[2024-09-24T18:54:16.520+0000] {logging_mixin.py:188} INFO - [CV] END max_depth=30, min_samples_split=10, n_estimators=50; total time=   0.1s
[2024-09-24T18:54:16.525+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:540 FitFailedWarning:
10 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/home/***/.local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/***/.local/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/home/***/.local/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/***/.local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of RandomForestClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.
[2024-09-24T18:54:16.527+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/model_selection/_search.py:1102 UserWarning: One or more of the test scores are non-finite: [       nan 0.81321777        nan 0.80755442]
[2024-09-24T18:54:16.627+0000] {hw1-checkpoint.py:171} INFO - Finish model train.
[2024-09-24T18:54:16.628+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-24T18:54:16.629+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-24T18:54:16.636+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=random_forest_classifier_dag, task_id=rfc_train_model, run_id=manual__2024-09-24T18:54:05.214006+00:00, execution_date=20240924T185405, start_date=20240924T185414, end_date=20240924T185416
[2024-09-24T18:54:16.672+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-24T18:54:16.688+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-24T18:54:16.691+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
