[2024-10-02T13:55:17.164+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T13:55:17.189+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: decision_tree_classifier_dag.dtc_save_results scheduled__2024-10-01T01:00:00+00:00 [queued]>
[2024-10-02T13:55:17.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: decision_tree_classifier_dag.dtc_save_results scheduled__2024-10-01T01:00:00+00:00 [queued]>
[2024-10-02T13:55:17.203+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T13:55:17.229+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dtc_save_results> on 2024-10-01 01:00:00+00:00
[2024-10-02T13:55:17.241+0000] {standard_task_runner.py:64} INFO - Started process 1262 to run task
[2024-10-02T13:55:17.245+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'decision_tree_classifier_dag', 'dtc_save_results', 'scheduled__2024-10-01T01:00:00+00:00', '--job-id', '631', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/hw1-checkpoint.py', '--cfg-path', '/tmp/tmpbv4sm2n5']
[2024-10-02T13:55:17.248+0000] {standard_task_runner.py:91} INFO - Job 631: Subtask dtc_save_results
[2024-10-02T13:55:17.323+0000] {task_command.py:426} INFO - Running <TaskInstance: decision_tree_classifier_dag.dtc_save_results scheduled__2024-10-01T01:00:00+00:00 [running]> on host 82997fc6deb7
[2024-10-02T13:55:17.462+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='decision_tree_classifier_dag' AIRFLOW_CTX_TASK_ID='dtc_save_results' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T01:00:00+00:00'
[2024-10-02T13:55:17.464+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T13:55:17.479+0000] {hw1-checkpoint.py:167} INFO - Save metrics...
[2024-10-02T13:55:17.644+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-02T13:55:17.646+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-02T13:55:18.426+0000] {hw1-checkpoint.py:194} INFO - DONE!!!
[2024-10-02T13:55:18.429+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T13:55:18.430+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T13:55:18.445+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=decision_tree_classifier_dag, task_id=dtc_save_results, run_id=scheduled__2024-10-01T01:00:00+00:00, execution_date=20241001T010000, start_date=20241002T135517, end_date=20241002T135518
[2024-10-02T13:55:18.505+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-02T13:55:18.530+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T13:55:18.535+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
