[2024-10-03T08:41:01.836+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-03T08:41:01.850+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gradient_boosting_classifier_dag.gbc_train_model scheduled__2024-10-02T01:00:00+00:00 [queued]>
[2024-10-03T08:41:01.857+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gradient_boosting_classifier_dag.gbc_train_model scheduled__2024-10-02T01:00:00+00:00 [queued]>
[2024-10-03T08:41:01.857+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-03T08:41:01.868+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): gbc_train_model> on 2024-10-02 01:00:00+00:00
[2024-10-03T08:41:01.876+0000] {standard_task_runner.py:64} INFO - Started process 640 to run task
[2024-10-03T08:41:01.879+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gradient_boosting_classifier_dag', 'gbc_train_model', 'scheduled__2024-10-02T01:00:00+00:00', '--job-id', '758', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/hw1.py', '--cfg-path', '/tmp/tmp7llh3hkn']
[2024-10-03T08:41:01.882+0000] {standard_task_runner.py:91} INFO - Job 758: Subtask gbc_train_model
[2024-10-03T08:41:01.918+0000] {task_command.py:426} INFO - Running <TaskInstance: gradient_boosting_classifier_dag.gbc_train_model scheduled__2024-10-02T01:00:00+00:00 [running]> on host 4b5f1410d111
[2024-10-03T08:41:01.986+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='gradient_boosting_classifier_dag' AIRFLOW_CTX_TASK_ID='gbc_train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T01:00:00+00:00'
[2024-10-03T08:41:01.988+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-03T08:41:01.996+0000] {hw1.py:137} INFO - Train model...
[2024-10-03T08:41:01.997+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/GradientBoostingClassifier/datasets/X_train.pkl
[2024-10-03T08:41:02.005+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-03T08:41:02.006+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-03T08:41:02.613+0000] {hw1.py:78} INFO - /tmp/***_tmp_t0c5y8yl
[2024-10-03T08:41:02.616+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/GradientBoostingClassifier/datasets/X_test.pkl
[2024-10-03T08:41:02.622+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-03T08:41:02.623+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-03T08:41:02.874+0000] {hw1.py:78} INFO - /tmp/***_tmp_0k39xx5e
[2024-10-03T08:41:02.877+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/GradientBoostingClassifier/datasets/y_train.pkl
[2024-10-03T08:41:02.883+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-03T08:41:02.885+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-03T08:41:03.079+0000] {hw1.py:78} INFO - /tmp/***_tmp_fk4jr8a0
[2024-10-03T08:41:03.081+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/GradientBoostingClassifier/datasets/y_test.pkl
[2024-10-03T08:41:03.091+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-03T08:41:03.092+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-03T08:41:03.494+0000] {hw1.py:78} INFO - /tmp/***_tmp_b0ud7oie
[2024-10-03T08:41:03.500+0000] {logging_mixin.py:188} INFO - Fitting 5 folds for each of 1080 candidates, totalling 5400 fits
[2024-10-03T08:41:03.535+0000] {logging_mixin.py:188} INFO - [CV] END ..learning_rate=0.001, max_depth=1, n_estimators=50; total time=   0.0s
[2024-10-03T08:41:03.565+0000] {logging_mixin.py:188} INFO - [CV] END ..learning_rate=0.001, max_depth=1, n_estimators=50; total time=   0.0s
[2024-10-03T08:41:03.594+0000] {logging_mixin.py:188} INFO - [CV] END ..learning_rate=0.001, max_depth=1, n_estimators=50; total time=   0.0s
[2024-10-03T08:41:03.629+0000] {logging_mixin.py:188} INFO - [CV] END ..learning_rate=0.001, max_depth=1, n_estimators=50; total time=   0.0s
[2024-10-03T08:41:03.658+0000] {logging_mixin.py:188} INFO - [CV] END ..learning_rate=0.001, max_depth=1, n_estimators=50; total time=   0.0s
[2024-10-03T08:41:03.714+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=100; total time=   0.1s
[2024-10-03T08:41:03.767+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=100; total time=   0.1s
[2024-10-03T08:41:03.818+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=100; total time=   0.0s
[2024-10-03T08:41:03.868+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=100; total time=   0.0s
[2024-10-03T08:41:03.918+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=100; total time=   0.0s
[2024-10-03T08:41:03.992+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=150; total time=   0.1s
[2024-10-03T08:41:04.068+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=150; total time=   0.1s
[2024-10-03T08:41:04.159+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=150; total time=   0.1s
[2024-10-03T08:41:04.243+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=150; total time=   0.1s
[2024-10-03T08:41:04.315+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=150; total time=   0.1s
[2024-10-03T08:41:04.417+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=200; total time=   0.1s
[2024-10-03T08:41:04.529+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=200; total time=   0.1s
[2024-10-03T08:41:04.628+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=200; total time=   0.1s
[2024-10-03T08:41:04.719+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=200; total time=   0.1s
[2024-10-03T08:41:04.824+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=200; total time=   0.1s
[2024-10-03T08:41:04.935+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=250; total time=   0.1s
[2024-10-03T08:41:05.048+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=250; total time=   0.1s
[2024-10-03T08:41:05.171+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=250; total time=   0.1s
[2024-10-03T08:41:05.296+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=250; total time=   0.1s
[2024-10-03T08:41:05.423+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=250; total time=   0.1s
[2024-10-03T08:41:05.559+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=300; total time=   0.1s
[2024-10-03T08:41:05.710+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=300; total time=   0.1s
[2024-10-03T08:41:05.865+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=300; total time=   0.2s
[2024-10-03T08:41:05.999+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=300; total time=   0.1s
[2024-10-03T08:41:06.143+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=300; total time=   0.1s
[2024-10-03T08:41:06.310+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=350; total time=   0.2s
[2024-10-03T08:41:06.492+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=350; total time=   0.2s
[2024-10-03T08:41:06.651+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=350; total time=   0.2s
[2024-10-03T08:41:06.824+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=350; total time=   0.2s
[2024-10-03T08:41:06.989+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=350; total time=   0.2s
[2024-10-03T08:41:07.161+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=400; total time=   0.2s
[2024-10-03T08:41:07.330+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=400; total time=   0.2s
[2024-10-03T08:41:07.510+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=400; total time=   0.2s
[2024-10-03T08:41:07.733+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=400; total time=   0.2s
[2024-10-03T08:41:07.946+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=400; total time=   0.2s
[2024-10-03T08:41:08.142+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=450; total time=   0.2s
[2024-10-03T08:41:08.339+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=450; total time=   0.2s
[2024-10-03T08:41:08.550+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=450; total time=   0.2s
[2024-10-03T08:41:08.760+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=450; total time=   0.2s
[2024-10-03T08:41:08.981+0000] {logging_mixin.py:188} INFO - [CV] END .learning_rate=0.001, max_depth=1, n_estimators=450; total time=   0.2s
[2024-10-03T08:41:09.036+0000] {logging_mixin.py:188} INFO - [CV] END ..learning_rate=0.001, max_depth=3, n_estimators=50; total time=   0.1s
[2024-10-03T08:41:09.082+0000] {logging_mixin.py:188} INFO - [CV] END ..learning_rate=0.001, max_depth=3, n_estimators=50; total time=   0.0s
[2024-10-03T08:41:09.147+0000] {logging_mixin.py:188} INFO - [CV] END ..learning_rate=0.001, max_depth=3, n_estimators=50; total time=   0.1s
[2024-10-03T08:41:09.192+0000] {logging_mixin.py:188} INFO - [CV] END ..learning_rate=0.001, max_depth=3, n_estimators=50; total time=   0.0s
[2024-10-03T08:41:09.243+0000] {logging_mixin.py:188} INFO - [CV] END ..learning_rate=0.001, max_depth=3, n_estimators=50; total time=   0.0s
[2024-10-03T08:41:09.270+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2024-10-03T08:41:09.277+0000] {process_utils.py:132} INFO - Sending 15 to group 640. PIDs of all processes in the group: [640]
[2024-10-03T08:41:09.282+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 640
[2024-10-03T08:41:09.283+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-03T08:41:09.289+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-03T08:41:09.302+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow/dags/hw1.py", line 150, in train_model
    grid_search.fit(X_train, y_train)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 1018, in fit
    self._run_search(evaluate_candidates)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 1572, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 964, in evaluate_candidates
    out = parallel(
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 74, in __call__
    return super().__call__(iterable_with_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
  File "/home/airflow/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 136, in __call__
    return self.function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 783, in fit
    n_stages = self._fit_stages(
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 879, in _fit_stages
    raw_predictions = self._fit_stage(
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 490, in _fit_stage
    tree.fit(
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/tree/_classes.py", line 1377, in fit
    super()._fit(
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/tree/_classes.py", line 472, in _fit
    builder.build(self.tree_, X, y, sample_weight, missing_values_in_feature_mask)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-10-03T08:41:09.311+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=gradient_boosting_classifier_dag, task_id=gbc_train_model, run_id=scheduled__2024-10-02T01:00:00+00:00, execution_date=20241002T010000, start_date=20241003T084101, end_date=20241003T084109
[2024-10-03T08:41:09.328+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-10-03T08:41:09.329+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-10-03T08:41:09.329+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-10-03T08:41:09.335+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-10-03T08:41:09.335+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-10-03T08:41:09.336+0000] {taskinstance.py:879} ERROR - Failed to send email to: alexvlg34@gmail.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2676, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2701, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow/dags/hw1.py", line 150, in train_model
    grid_search.fit(X_train, y_train)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 1018, in fit
    self._run_search(evaluate_candidates)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 1572, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 964, in evaluate_candidates
    out = parallel(
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 74, in __call__
    return super().__call__(iterable_with_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
  File "/home/airflow/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 136, in __call__
    return self.function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 783, in fit
    n_stages = self._fit_stages(
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 879, in _fit_stages
    raw_predictions = self._fit_stage(
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 490, in _fit_stage
    tree.fit(
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/tree/_classes.py", line 1377, in fit
    super()._fit(
  File "/home/airflow/.local/lib/python3.10/site-packages/sklearn/tree/_classes.py", line 472, in _fit
    builder.build(self.tree_, X, y, sample_weight, missing_values_in_feature_mask)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1063, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 877, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3163, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1065, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-10-03T08:41:09.378+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=640, status='terminated', exitcode=2, started='08:41:00') (640) terminated with exit code 2
[2024-10-03T08:41:09.379+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 143
[2024-10-03T08:41:09.397+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
